### ISSUE TITLE
Failed tests result is not processing

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/goost#60]
https://app.shippable.com/github/DronMDF/goost/runs/121/1/console

```
 ./test_report.py -o shippable/testresults/result.xml ./test_runner 21s  
Traceback (most recent call last):
  File "./test_report.py", line 62, in <module>
    Main(sys.argv[1:]).run()
  File "./test_report.py", line 57, in run
    log = self.log()
  File "./test_report.py", line 35, in log
    out = subprocess.check_output([self.options.runner(), '-t'])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./test_runner', '-t']' returned non-zero exit status 255
```

**Comment by DronMDF** [comment]
Related to #24
